# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11rqihncTqz5PkcRNTaPqHUSD1QZ5_8_Q
"""

import os
import re
import time
import datetime
import json
import pandas as pd
import numpy as np
from pypdf import PdfReader
import glob
import gradio as gr
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.chat_models import ChatOpenAI
from langchain.prompts import PromptTemplate
from langchain.memory import ConversationBufferMemory
from langchain.chains import ConversationalRetrievalChain
from openai import OpenAI
from langchain_community.vectorstores import Chroma

# Get API key from environment variables
# When deployed on Hugging Face Spaces, you'll set this as a secret
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

# Text extraction and processing functions
def extract_text_from_pdfs(pdf_dir="diet_pdfs"):
    """Extract text from all PDFs in the specified directory"""
    # Get all PDF files in the directory
    pdf_files = glob.glob(os.path.join(pdf_dir, "*.pdf"))

    if not pdf_files:
        # If no PDFs found, use sample data
        print("No PDF files found. Using sample data.")
        return generate_sample_data()

    print(f"Found {len(pdf_files)} PDF files: {[os.path.basename(f) for f in pdf_files]}")

    # Dictionary to store extracted text from each PDF
    extracted_texts = {}

    # Process each PDF file
    for pdf_path in pdf_files:
        try:
            pdf_reader = PdfReader(pdf_path)
            text = ""
            for page in pdf_reader.pages:
                text += page.extract_text()

            # Store text with filename as key
            filename = os.path.basename(pdf_path)
            extracted_texts[filename] = text
            print(f"Successfully extracted text from {filename}, {len(text)} characters")
        except Exception as e:
            print(f"Error extracting text from {os.path.basename(pdf_path)}: {str(e)}")

    return extracted_texts

def generate_sample_data():
    """Generate sample data if no PDFs are found"""
    return {
        "sample_north_indian.pdf": """
        North Indian Vegetarian Dishes:
        - Paneer Butter Masala: A rich and creamy curry made with paneer cheese, tomatoes, cream, and spices.
        - Aloo Gobi: A dry curry made with potatoes, cauliflower, and spices.
        - Chole Bhature: Spicy chickpea curry served with fried bread.
        - Dal Makhani: Slow-cooked black lentils with butter and cream.
        - Rajma: Kidney bean curry cooked with onions, tomatoes, and spices.

        North Indian Non-Vegetarian Dishes:
        - Butter Chicken: Tender chicken pieces in a rich tomato and butter sauce.
        - Rogan Josh: A Kashmiri lamb curry with a rich red sauce.
        - Chicken Biryani: Aromatic rice dish with chicken, spices, and saffron.

        Common Ingredients:
        - Garam masala, cumin, coriander, turmeric, red chili powder
        - Ghee (clarified butter), yogurt, cream
        - Onions, tomatoes, ginger, garlic
        - Basmati rice, whole wheat flour
        - Paneer (cottage cheese), potatoes, peas, cauliflower
        """,
        "sample_south_indian.pdf": """
        South Indian Vegetarian Dishes:
        - Dosa: Thin, crispy pancake made from fermented rice and lentil batter.
        - Idli: Steamed rice cakes made from fermented rice and lentil batter.
        - Sambar: Lentil soup with vegetables and tamarind.
        - Rasam: Tangy soup with tamarind, tomatoes, and spices.
        - Avial: Mixed vegetables cooked with coconut and yogurt.

        South Indian Non-Vegetarian Dishes:
        - Fish Curry: Spicy fish curry made with coconut milk and tamarind.
        - Chettinad Chicken: Chicken cooked with a complex blend of spices.
        - Prawn Masala: Prawns cooked with onions, tomatoes, and spices.

        Common Ingredients:
        - Curry leaves, mustard seeds, urad dal, chana dal
        - Coconut, coconut milk, coconut oil
        - Rice, rice flour, semolina
        - Tamarind, jaggery
        - Chilies, black pepper, asafoetida
        """
    }

def clean_text(text):
    """Clean and preprocess the extracted text"""
    # Remove extra whitespaces
    text = re.sub(r'\s+', ' ', text)
    # Remove special characters that aren't relevant
    text = re.sub(r'[^\w\s.,;:()-]', '', text)
    return text.strip()

def split_text_into_chunks(text, chunk_size=1000, chunk_overlap=200):
    """Split text into overlapping chunks"""
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        length_function=len
    )
    chunks = text_splitter.split_text(text)
    return chunks

def create_vector_store(collection_name="dietician-assistant", pdf_dir="diet_pdfs"):
    """Create a vector store from PDFs using ChromaDB"""
    # Extract text from all PDFs in the directory
    extracted_texts = extract_text_from_pdfs(pdf_dir)

    all_chunks = []
    all_metadata = []

    # Process each extracted text
    chunk_id_counter = 0
    for filename, text in extracted_texts.items():
        cleaned_text = clean_text(text)
        chunks = split_text_into_chunks(cleaned_text)

        for i, chunk in enumerate(chunks):
            all_chunks.append(chunk)
            all_metadata.append({"source": filename, "chunk_id": i})
            chunk_id_counter += 1

    print(f"Created {len(all_chunks)} chunks from all PDFs/sample data")

    # Initialize embeddings for LangChain
    embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

    # Set up ChromaDB persistent directory
    persist_directory = "chroma_db"

    # Create Chroma vector store from the documents (LangChain interface)
    print(f"Uploading {len(all_chunks)} chunks to ChromaDB...")
    try:
        # Create the vector store
        vector_store = Chroma.from_texts(
            texts=all_chunks,
            embedding=embeddings,
            metadatas=all_metadata,
            persist_directory=persist_directory
        )

        # Persist the vector store to disk
        vector_store.persist()

        print("Vector store creation complete!")
        return vector_store

    except Exception as e:
        print(f"Error creating vector store: {str(e)}")
        raise

def setup_rag_model(vector_store):
    """Set up the RAG model with appropriate prompts"""
    # Create LLM
    chatgpt = ChatOpenAI(model_name='gpt-4o-mini', temperature=0)

    # Create memory
    memory = ConversationBufferMemory(
        memory_key="chat_history",
        return_messages=True
    )

    # Create the prompt template for different use cases
    toddler_diet_template = """
    You are a professional pediatric nutritionist specializing in Indian cuisine.
    Use the following information from the nutritional database and your own knowledge to create tailored weekly nutrition plan for a 4-year-old toddler.
    Consider the child's nutritional needs for growth and development.

    Context information from nutrition database: {context}

    Include:
    - Breakfast, Brunch, Lunch, Snacks, Dinner
    - Day-wise plan
    - Calories per meal (approx)

    Chat History: {chat_history}

    Question: {question}
    """

    adult_diet_template = """
    You are a professional nutritionist specializing in Indian cuisine and weight loss.
    Use the following information from the nutritional database and your own knowledge, to create a weekly weight loss diet plan for adults aged 36 and 42
    who want to lose weight while maintaining proper nutrition.

    Context information from nutrition database: {context}

    Include:
    - Breakfast, Lunch, Snacks, Dinner
    - Day-wise plan
    - Calories per meal (approx)
    - Balance of protein, fiber, and carbs

    Chat History: {chat_history}

    Question: {question}

    Return the output as a markdown table.
    """

    # Create the prompt templates
    TODDLER_PROMPT = PromptTemplate(
        input_variables=["context", "chat_history", "question"],
        template=toddler_diet_template,
    )

    ADULT_PROMPT = PromptTemplate(
        input_variables=["context", "chat_history", "question"],
        template=adult_diet_template,
    )

    # Create the RAG chain for toddler
    toddler_qa_chain = ConversationalRetrievalChain.from_llm(
        llm=chatgpt,
        retriever=vector_store.as_retriever(search_kwargs={"k": 5}),
        memory=memory,
        combine_docs_chain_kwargs={"prompt": TODDLER_PROMPT}
    )

    # Create the RAG chain for adults
    adult_qa_chain = ConversationalRetrievalChain.from_llm(
        llm=chatgpt,
        retriever=vector_store.as_retriever(search_kwargs={"k": 5}),
        memory=memory,
        combine_docs_chain_kwargs={"prompt": ADULT_PROMPT}
    )

    return {
        "toddler": toddler_qa_chain,
        "adult": adult_qa_chain
    }

# Function to generate diet plans
def generate_diet_plan(rag_chains, user_type, query):
    """Generate diet plan based on user query"""
    if user_type not in rag_chains:
        return "Invalid user type. Please choose 'toddler' or 'adult'."

    chain = rag_chains[user_type]
    response = chain({"question": query})
    return response["answer"]

# Create a function to generate a weekly diet plan
def generate_weekly_diet_plan(rag_chains, user_type):
    """Generate a complete weekly diet plan"""
    if user_type == "toddler":
        query = """
        Create a detailed 7-day Indian diet plan for a 4-year-old toddler in tabular format with the following structure:
        1. For each day, include breakfast, mid-morning snack, lunch, evening snack, and dinner
        2. For each meal, specify portion sizes appropriate for a 4-year-old
        3. Ensure variety and balanced nutrition with focus on growth and development
        4. Include information about essential nutrients included in each day's plan
        5. Suggest creative ways to make meals appealing for children
        6. Avoid cheese cubes.
        7. Lunch should contain roti or rice or both roti and rice.
        Use the Indian recipes when possible.
        """
    else:  # adult
        query = """
        Create a detailed 7-day Indian weight loss diet plan for adults (36 and 42 years old) in tabular format with the following structure:
        1. For each day, include breakfast, mid-morning snack, lunch, evening snack, and dinner
        2. For each meal, specify portion sizes and approximate calorie counts
        3. Ensure variety and balanced nutrition with focus on weight loss
        4. Include information about macronutrient distribution (protein, carbs, fats)
        5. Suggest meal prep tips to make following the plan easier
        Use the Indian recipes when possible.
        """

    return generate_diet_plan(rag_chains, user_type, query)

# Function to process nutritional information for specific recipes
def get_recipe_nutrition(rag_chains, recipe_name):
    """Get nutritional information for a specific recipe"""
    query = f"Provide detailed nutritional information for the recipe '{recipe_name}', including calories, proteins, carbohydrates, fats, and essential vitamins and minerals."

    # Use the adult chain for recipe queries as it's more comprehensive
    response = generate_diet_plan(rag_chains, "adult", query)
    return response

def get_recipe(recipe_name):
    """Get recipe preparation instructions for a specific dish"""
    try:
        # Create a new OpenAI client instance
        client = OpenAI(api_key=OPENAI_API_KEY)

        # Create a prompt for recipe preparation
        RECIPE_PROMPT = f"""
        You are a helpful culinary assistant who provides detailed recipe instructions.
        Provide a detailed recipe for preparing {recipe_name}. Include:

        1. List of ingredients with measurements
        2. Step-by-step preparation instructions
        3. Approximate cooking time
        4. Nutrition information if available
        5. Any tips for dietary modifications
        """

        # Call the OpenAI API to generate the recipe
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You are a helpful culinary assistant."},
                {"role": "user", "content": RECIPE_PROMPT}
            ],
            max_tokens=800,
            temperature=0.7
        )

        # Check if the response contains the expected fields
        if response and hasattr(response, 'choices') and len(response.choices) > 0:
            return response.choices[0].message.content
        else:
            return "Sorry, I couldn't generate a recipe. Please try again."

    except Exception as e:
        print(f"Error in get_recipe: {str(e)}")
        return f"Error generating recipe: {str(e)}"

# Gradio UI Class
class DieticianAssistantUI:
    def __init__(self, vector_store, rag_chains):
        self.vector_store = vector_store
        self.rag_chains = rag_chains
        self.openai_api_key = OPENAI_API_KEY

        # Create a directory for saved plans if it doesn't exist
        self.save_dir = "saved_meal_plans"
        if not os.path.exists(self.save_dir):
            os.makedirs(self.save_dir)

        # Initialize history storage
        self.history_file = os.path.join(self.save_dir, "request_history.json")
        if os.path.exists(self.history_file):
            with open(self.history_file, 'r') as f:
                self.history = json.load(f)
        else:
            self.history = {
                "toddler_plans": [],
                "adult_plans": [],
                "nutrition_queries": [],
                "recipe_queries": []
            }
            self._save_history()

    def _save_history(self):
        """Save history to file"""
        with open(self.history_file, 'w') as f:
            json.dump(self.history, f, indent=2)

    def _add_to_history(self, category, query, content=None, timestamp=None):
        """Add an item to history with content"""
        if timestamp is None:
            timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Store first line of content as preview
        preview = ""
        if content:
            # First line only for preview
            first_line = content.split('\n')[0] if '\n' in content else content
            preview = first_line

        self.history[category].append({
            "query": query,
            "timestamp": timestamp,
            "preview": preview
        })

        if len(self.history[category]) > 10:  # Keep only last 10 items
            self.history[category] = self.history[category][-10:]
        self._save_history()

    def _get_history_text(self):
        """Generate formatted history text"""
        history_text = "# Recent Request History\n\n"

        if self.history["toddler_plans"]:
            history_text += "## Toddler Meal Plans\n"
            for item in reversed(self.history["toddler_plans"]):
                preview = item.get('preview', '')
                if preview:
                    history_text += f"- {item['timestamp']}: Generated toddler meal plan\n  *Preview: {preview}*\n\n"
                else:
                    history_text += f"- {item['timestamp']}: Generated toddler meal plan\n\n"

        if self.history["adult_plans"]:
            history_text += "## Adult Weight Loss Plans\n"
            for item in reversed(self.history["adult_plans"]):
                preview = item.get('preview', '')
                if preview:
                    history_text += f"- {item['timestamp']}: Generated adult weight loss plan\n  *Preview: {preview}*\n\n"
                else:
                    history_text += f"- {item['timestamp']}: Generated adult weight loss plan\n\n"

        if self.history["nutrition_queries"]:
            history_text += "## Nutrition Queries\n"
            for item in reversed(self.history["nutrition_queries"]):
                preview = item.get('preview', '')
                if preview:
                    history_text += f"- {item['timestamp']}: {item['query']}\n  *Preview: {preview}*\n\n"
                else:
                    history_text += f"- {item['timestamp']}: {item['query']}\n\n"

        if self.history["recipe_queries"]:
            history_text += "## Recipe Queries\n"
            for item in reversed(self.history["recipe_queries"]):
                preview = item.get('preview', '')
                if preview:
                    history_text += f"- {item['timestamp']}: {item['query']}\n  *Preview: {preview}*\n\n"
                else:
                    history_text += f"- {item['timestamp']}: {item['query']}\n\n"

        return history_text

    def generate_toddler_plan(self):
        """Generate weekly diet plan for toddler"""
        # Simple text output to show processing
        time.sleep(0.5)  # Small delay to show the message is updating
        processing_message = "⏳ Generating toddler meal plan... This may take a minute."
        yield processing_message

        # Generate the plan
        plan = generate_weekly_diet_plan(self.rag_chains, "toddler")

        # Save to history with content
        self._add_to_history("toddler_plans", "Toddler meal plan", plan)

        # Return the complete plan
        yield plan

    def generate_adult_plan(self):
        """Generate weekly diet plan for adults"""
        # Simple text output to show processing
        time.sleep(0.5)  # Small delay to show the message is updating
        processing_message = "⏳ Generating adult weight loss meal plan... This may take a minute."
        yield processing_message

        # Generate the plan
        plan = generate_weekly_diet_plan(self.rag_chains, "adult")

        # Save to history with content
        self._add_to_history("adult_plans", "Adult weight loss plan", plan)

        # Return the complete plan
        yield plan

    def get_nutrition_info(self, recipe_name):
        """Get nutritional information for a specific recipe"""
        if not recipe_name or recipe_name.strip() == "":
            yield "Please enter a recipe name."
            return

        # Simple text output to show processing
        time.sleep(0.5)  # Small delay to show the message is updating
        processing_message = f"⏳ Analyzing nutrition for {recipe_name}... This may take a minute."
        yield processing_message

        # Get the information
        info = get_recipe_nutrition(self.rag_chains, recipe_name)

        # Save to history with content
        self._add_to_history("nutrition_queries", recipe_name, info)

        # Return the complete information
        yield info

    def get_recipe_instructions(self, recipe_name):
        """Get recipe preparation instructions"""
        if not recipe_name or recipe_name.strip() == "":
            yield "Please enter a dish name."
            return

        # Simple text output to show processing
        time.sleep(0.5)  # Small delay to show the message is updating
        processing_message = f"⏳ Preparing recipe for {recipe_name}... This may take a minute."
        yield processing_message

        try:
            # Get recipe using the standalone function
            recipe = get_recipe(recipe_name)

            # Save to history with content
            self._add_to_history("recipe_queries", recipe_name, recipe)

            yield recipe
        except Exception as e:
            yield f"Error generating recipe: {str(e)}"

    def refresh_history(self):
        """Refresh the history display"""
        return self._get_history_text()

    def create_ui(self):
        """Create the Gradio interface"""
        with gr.Blocks(title="Dietician Assistant") as app:
            gr.Markdown("# 🥗 AI-Powered Dietician Assistant")
            gr.Markdown("Your personalized nutrition guide powered by AI and expert knowledge")

            with gr.Tabs() as tabs:
                with gr.TabItem("🧒 Toddler Meal Plan"):
                    with gr.Row():
                        with gr.Column(scale=1):
                            toddler_generate_btn = gr.Button("Generate Weekly Plan for 4-year-old", variant="primary")
                        with gr.Column(scale=3):
                            toddler_output = gr.Markdown()

                    toddler_generate_btn.click(
                        fn=self.generate_toddler_plan,
                        outputs=toddler_output
                    )

                with gr.TabItem("👨‍👩‍👧 Adult Weight Loss Plan"):
                    with gr.Row():
                        with gr.Column(scale=1):
                            adult_generate_btn = gr.Button("Generate Weight Loss Plan", variant="primary")
                        with gr.Column(scale=3):
                            adult_output = gr.Markdown()

                    adult_generate_btn.click(
                        fn=self.generate_adult_plan,
                        outputs=adult_output
                    )

                with gr.TabItem("🍲 Recipe Nutrition"):
                    with gr.Row():
                        with gr.Column(scale=1):
                            recipe_input = gr.Textbox(
                                label="Recipe Name",
                                placeholder="Enter a recipe (e.g., Palak Paneer)",
                                lines=1
                            )
                            nutrition_btn = gr.Button("Get Nutritional Info", variant="primary")
                        with gr.Column(scale=2):
                            nutrition_output = gr.Markdown()
                    nutrition_btn.click(
                        fn=self.get_nutrition_info,
                        inputs=recipe_input,
                        outputs=nutrition_output
                    )

                with gr.TabItem("👨‍🍳 Recipe Instructions"):
                    with gr.Row():
                        with gr.Column(scale=1):
                            dish_input = gr.Textbox(
                                label="Dish Name",
                                placeholder="Enter a dish (e.g., Butter Chicken)",
                                lines=1
                            )
                            recipe_btn = gr.Button("Get Recipe", variant="primary")
                        with gr.Column(scale=2):
                            recipe_output = gr.Markdown()
                    recipe_btn.click(
                        fn=self.get_recipe_instructions,
                        inputs=dish_input,
                        outputs=recipe_output
                    )

                with gr.TabItem("📜 History"):
                    with gr.Row():
                        with gr.Column():
                            history_output = gr.Markdown(value=self._get_history_text())
                            refresh_btn = gr.Button("Refresh History", variant="secondary")
                    refresh_btn.click(
                        fn=self.refresh_history,
                        outputs=history_output
                    )

            gr.Markdown("### 💡 Powered by LangChain and GPT-4o-mini")

        return app

    def launch(self, share=True):
        """Launch the UI"""
        app = self.create_ui()
        app.launch(share=share)

# Main function to initialize and run the assistant
def initialize_assistant():
    """Initialize and run the Dietician Assistant"""
    print("Welcome to the Dietician Assistant!")

    # Check if PDF directory exists, create if not
    pdf_dir = "diet_pdfs"
    if not os.path.exists(pdf_dir):
        os.makedirs(pdf_dir)
        print(f"Created directory {pdf_dir}. Please add your PDF files here.")

    try:
        # Step 1: Create vector store
        print("Processing PDFs and creating knowledge base...")
        vector_store = create_vector_store(collection_name="dietician-assistant", pdf_dir=pdf_dir)

        # Step 2: Set up RAG model
        print("Setting up the dietician assistant...")
        rag_chains = setup_rag_model(vector_store)

        # Step 3: Create and launch UI
        print("Initializing the user interface...")
        ui = DieticianAssistantUI(vector_store, rag_chains)
        return ui

    except Exception as e:
        print(f"Error initializing assistant: {str(e)}")
        raise

# Entry point for the application
if __name__ == "__main__":
    ui = initialize_assistant()
    ui.launch(share=False)  # Set share=False for production deployment